WebPhotoAlbum/Models/AdminUsers/UserAuthorVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebPhotoAlbum.Models.AdminUsers
{
    public class UserAuthorVM
    {
        public int Id { get; set; }
        public string UserName { get; set; }

        public string Name { get; set; }

        public string Surname { get; set; }

        public string Email { get; set; }

        public string Role { get; set; }

        public bool IsDeleted { get; set; }

    }
}

WebPhotoAlbum/Models/AdminUsers/UsersForAdminVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebPhotoAlbum.Models.AdminUsers
{
    public class UsersForAdminVM
    {
        public List<UserAuthorVM> Admins { get; set; }

        public List<UserAuthorVM> Authors { get; set; }

    }
}

WebPhotoAlbum/Controllers/AdminUsersController.cs
using AutoMapper;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebPhotoAlbum.BLL.DTO;
using WebPhotoAlbum.BLL.Interfaces.Services;
using WebPhotoAlbum.Models.AdminUsers;
using WebPhotoAlbum.Models.AuthorProfile;

namespace WebPhotoAlbum.Controllers
{
    [Authorize(Roles ="Admin")]
    public class AdminUsersController : Controller
    {
        private readonly IAuthorService authorService;
        private readonly IAdminService adminService;
        private readonly IMapper _mapper;
        public AdminUsersController(IAuthorService _authorService, IPostService _postService,IAdminService _adminService)
        {
            authorService = _authorService;
            adminService = _adminService;
            _mapper = new MapperConfiguration(cgf =>
            {
                cgf.CreateMap<AuthorDTO, UserAuthorVM>();

                cgf.CreateMap<AdminDTO, UserAuthorVM>();

            }).CreateMapper();
        } 
        /// <summary>
        ///Returns index view to user. 
        ///</summary>
        ///<returns>View with index page</returns>
        public ActionResult Index()
        {
            List<AuthorDTO> authorDTOs = authorService.GetAuthors();
            List<AdminDTO> adminDTOs = adminService.GetAdmins();
            List<UserAuthorVM> userAuthorVMs = _mapper.Map<List<AuthorDTO>, List<UserAuthorVM>>(authorDTOs);
            List<UserAuthorVM> userAdminVMs= _mapper.Map<List<AdminDTO>, List<UserAuthorVM>>(adminDTOs);
            UsersForAdminVM usersForAdminVM = new UsersForAdminVM();
            usersForAdminVM.Admins = userAdminVMs;
            usersForAdminVM.Authors = userAuthorVMs;
            return View(usersForAdminVM);
        }

        /// <summary>
        ///If user confirmed the deletion method delete post. 
        ///</summary>
        ///<param name="id">Post id.</param>
        ///<returns>Index view</returns>
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AuthorDTO authorDTO = authorService.GetAuthor((int)id);
            if (authorDTO== null)
            {
                return HttpNotFound();
            }
            return View(id);
        }

        /// <summary>
        ///If user confirmed the deletion method delete post. 
        ///</summary>
        ///<param name="id">Post id.</param>
        ///<returns>Index view</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            authorService.DeleteAuthor(id); 
        
            return RedirectToAction("Index");
        }
    }
}

WebPhotoAlbum/Views/AdminUsers/Delete.cshtml
@model int
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
   
}
</head>
<body>

    <div>
        <h3>Are you sure you want to delete this?</h3>
        @using (Html.BeginForm("Delete", "AdminDoctors", new { id = Model }))
        {@Html.AntiForgeryToken()

        <button class="btn btn-danger btn-xs" type="submit">Delete</button>
    }
    </div>
       
    </body>
</html>

WebPhotoAlbum/Views/AdminUsers/Index.cshtml
@using WebPhotoAlbum.Models.AdminUsers;
@model UsersForAdminVM
@{
    Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link type="text/css" rel="stylesheet" href="~/Content/Styles/AdminUsers.css" />
</head>
@Styles.Render("~/Content/css")
@Styles.Render("~/Content/Site.css")
@Scripts.Render("~/bundles/modernizr")

<body>

    <h2>Users accounts</h2>
    <div>
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th></th>
            </tr>
            @if (Model.Authors.Count() == 0)
            {
                <tr>
                    <td colspan="4" class="text-center">No accounts</td>
                </tr>
            }
            else
            {
                foreach (UserAuthorVM user in Model.Authors)
                {
        <tr>
            <td>@user.Id</td>
            <td>@user.Name</td>
            <td>@user.Email</td>
            <td>@user.Role</td>
            <td>@user.IsDeleted</td>
            <td>
                @using (Html.BeginForm("Delete", "AdminUsers", new { id = user.Id }))
                {
                    @Html.AntiForgeryToken()
                    <button class="btn btn-danger btn-xs" type="submit">Delete</button>}
            </td>
        </tr>
                }
            }
        </table>
    </div>
    <h2>Admin accounts</h2>
    <div>
        <table class="table">
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th></th>
            </tr>
            @if (Model.Admins.Count() == 0)
            {
                <tr>
                    <td colspan="4" class="text-center">No accounts</td>
                </tr>
            }
            else
            {
                foreach (UserAuthorVM user in Model.Admins)
                {
        <tr>
            <td>@user.Id</td>
            <td>@user.Name</td>
            <td>@user.Email</td>
            <td>@user.Role</td>
        </tr>
                }
            }
        </table>
    </div>
</body>
</html>