WebPhotoAlbum/Models/AuthorProfile/AuthorProfileVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPhotoAlbum.Models.Home;

namespace WebPhotoAlbum.Models.AuthorProfile
{
    public class AuthorProfileVM
    {
        public int Id { get; set; }

        public string UserName { get; set; }

        public string Name { get; set; }

        public string Surname { get; set; }

        public List<DisplayPostVM> DisplayPostVMs { get; set; }

    }
}

WebPhotoAlbum/Models/AuthorProfile/EditAuthorProfileVM.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace WebPhotoAlbum.Models.AuthorProfile
{
    public class EditAuthorProfileVM
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Name")]
        public string Name { get; set; }
        [Required]
        [Display(Name = "Surname")]
        public string Surname { get; set; }


        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

 
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [DataType(DataType.Password)]
        [Compare("Password")]
        public string ConfirmPassword { get; set; }

    }
}

WebPhotoAlbum/Controllers/AuthorProfileController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebPhotoAlbum.BLL.DTO;
using WebPhotoAlbum.BLL.Infrastructure;
using WebPhotoAlbum.BLL.Interfaces.Services;
using WebPhotoAlbum.Models.AuthorProfile;
using WebPhotoAlbum.Models.Home;

namespace WebPhotoAlbum.Controllers
{
    [Authorize(Roles = "Author")]
    public class AuthorProfileController : Controller
    {
        private readonly IAuthorService authorService;
        private readonly IMapper _mapper;
        private readonly IPostService postService;
        public AuthorProfileController(IAuthorService _authorService, IPostService _postService)
        {

            authorService = _authorService;
            postService = _postService;
            _mapper = new MapperConfiguration(cgf =>
            {
                cgf.CreateMap<AuthorDTO, AuthorProfileVM>().ReverseMap();
                cgf.CreateMap<AuthorDTO, EditAuthorProfileVM>().ReverseMap();
                cgf.CreateMap<UpdateAuthorDTO, EditAuthorProfileVM>().ReverseMap();
                cgf.CreateMap<PostDTO, DisplayPostVM>().ReverseMap();


            }).CreateMapper();
        }

        /// <summary>
        ///Returns view with author profile. 
        ///</summary>
        ///<param name="id">Post id.</param>
        ///<returns>Author profile view</returns>
        public ActionResult Index()
        {
            AuthorDTO authorDTO = authorService.GetAuthor(User.Identity.GetUserId<int>());
            if (authorDTO == null)
            {
                return RedirectToAction("Login", "Account");
            }
            AuthorProfileVM authorProfileVM = _mapper.Map<AuthorDTO, AuthorProfileVM>(authorDTO);
            List<PostDTO> postDTOs = postService.GetPostsByAuthor(User.Identity.GetUserId<int>());
            List<DisplayPostVM> postVMs = new List<DisplayPostVM>();
            if (authorProfileVM.DisplayPostVMs == null)
            {
                authorProfileVM.DisplayPostVMs = new List<DisplayPostVM>();
            }

            foreach (PostDTO postDTO in postDTOs)
            {
                DisplayPostVM displayPostVM = new DisplayPostVM()
                {
                    Id = postDTO.Id,
                    ImageData = postDTO.ImageData,
                    ImageMimeType = postDTO.ImageMimeType,

                };
                postVMs.Add(displayPostVM);


            }
            postVMs.Reverse();
            Session["NextAuthorPosts"] = postVMs;


            authorProfileVM.DisplayPostVMs = postVMs;
            return View(authorProfileVM);
        }
        /// <summary>
        ///Returns view with author profile for editing. 
        ///</summary>

        [HttpGet]
        public ActionResult EditAuthorProfile()
        {
            AuthorDTO authorDTO = authorService.GetAuthor(User.Identity.GetUserId<int>());
            if (authorDTO == null)
            {
                return RedirectToAction("Login", "Account");
            }
            EditAuthorProfileVM authorProfileVM = _mapper.Map<AuthorDTO, EditAuthorProfileVM>(authorDTO);

            return View(authorProfileVM);

        }
        /// <summary>
        ///Returns view with author profile for editing. 
        ///</summary>
        ///<param name="authorProfileVM">Edited profile data.</param>
        ///<returns>If succeed returns to author profile else shows errors on edit view</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditAuthorProfile(EditAuthorProfileVM authorProfileVM)
        {
            if (ModelState.IsValid)
            {

                OperationDetails operationDetails = authorService.UpdateAuthor(_mapper.Map<EditAuthorProfileVM, UpdateAuthorDTO>(authorProfileVM));
                if (operationDetails.Succedeed)
                    return RedirectToAction("Index", "AuthorProfile");
                else
                    ModelState.AddModelError(operationDetails.Property, operationDetails.Message);
            }
            return View(authorProfileVM);

        }





    }
}

WebPhotoAlbum/Controllers/PostController.cs
using AutoMapper;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WebPhotoAlbum.BLL.DTO;
using WebPhotoAlbum.BLL.Interfaces.Services;
using WebPhotoAlbum.Helpers;
using WebPhotoAlbum.Models.Home;
using WebPhotoAlbum.Models.Post;
using WebPhotoAlbum.Models.Rating;
using WebPhotoAlbum.Models.Tag;

namespace WebPhotoAlbum.Controllers
{
    [Authorize(Roles = "Author")]
    public class PostController : Controller
    {
        // GET: Post
        private readonly IPostService postService;

        private readonly IAuthorService authorService;

        private readonly IRatingService ratingService;

        private readonly IMapper _mapper;
        public PostController(IPostService _postService, IAuthorService _authorService, IRatingService _ratingService)
        {
            postService = _postService;

            authorService = _authorService;

            ratingService = _ratingService;

            _mapper = new MapperConfiguration(cgf =>
            {
                cgf.CreateMap<PostDTO, PostVM>().ReverseMap();
                cgf.CreateMap<TagDTO, TagVM>().ReverseMap();
                cgf.CreateMap<PostDTO, SinglePostVM>().ForMember(dest => dest.Tags,
                      opt => opt.MapFrom(
                         src => (_mapper.Map<ICollection<TagDTO>, ICollection<TagVM>>(src.Tags)))).ReverseMap();
                cgf.CreateMap<PostDTO, DisplayPostVM>().ReverseMap();

            }).CreateMapper();
        }
       
        public ActionResult Index()
        {

            return View(new PostVM());
        }
        /// <summary>
        ///Returns partial view with new post modal. 
        ///</summary>

        ///<returns> Partial view with new post modal</returns>
        [HttpGet]
        public ActionResult CreatePost()
        {

            Session["Tags"] = new List<TagVM>();
            return PartialView("~/Views/Post/Partial/NewPostPartialView.cshtml", new PostVM());

        }
        /// <summary>
        ///Create new post. 
        ///</summary>
        ///<param name="postVM">New post.</param>
        ///<returns>Redirect to index author profile</returns>
        [HttpPost]
        public ActionResult CreatePost(PostVM postVM)
        {
            if (ModelState.IsValid)
            {

                PostDTO postDTO = new PostDTO();
                postDTO.Description = postVM.Description;
                Bitmap bmp;


                if (postVM.InputImage != null)
                {
                    postDTO.ImageMimeType = postVM.InputImage.ContentType;
                    postDTO.ImageData = new byte[postVM.InputImage.ContentLength];
                    postVM.InputImage.InputStream.Read(postDTO.ImageData, 0, postVM.InputImage.ContentLength);
                }


                postDTO.Tags = _mapper.Map<ICollection<TagVM>, ICollection<TagDTO>>(Session["Tags"] as ICollection<TagVM>);
                postDTO.AuthorId = User.Identity.GetUserId<int>();

                postService.Create(postDTO);
            }
            return RedirectToAction("Index", "AuthorProfile");

        }
        /// <summary>
        ///Gets next posts and returns partial view with next posts. 
        ///</summary>
        ///<param name="pageCount">Number of page.</param>
        ///<param name="searchText">Text to search.</param>
        ///<returns> Partial view with next posts</returns>
        [HttpPost]
        [AllowAnonymous]
        public ActionResult GetNextPosts(int pageCount, string searchText)
        {
            int pageSize = Int32.Parse(ConfigurationSettings.AppSettings["PageSize"]);
            List<PostDTO> postDTOs = postService.GetPostsWithSkip(pageCount *pageSize, pageSize, searchText);
            List<DisplayPostVM> postVMs = new List<DisplayPostVM>();

            _mapper.Map<List<PostDTO>, List<DisplayPostVM>>(postDTOs, postVMs);

            List<DisplayPostVM> displayPostVMs = (Session["NextPosts"] as List<DisplayPostVM>);
            displayPostVMs.AddRange(postVMs);
            Session["NextPosts"] = displayPostVMs;
            return PartialView("~/Views/Home/Partial/ListOfPostsView.cshtml", postVMs);
        }



        [HttpPost]
        public ActionResult DenyCreating(int Id)
        {
            postService.Delete(Id);

            return RedirectToAction("Index", "AuthorProfile");
        }
        /// <summary>
        ///Returns necessary image to home. 
        ///</summary>
        ///<param name="id">Id of post.</param>
        ///<returns>Necessary image</returns>
        [AllowAnonymous]
        public ActionResult GetPostImageToGridItem(int Id)
        {
          
            List<DisplayPostVM> displayPostVMs = (Session["NextPosts"] as List<DisplayPostVM>);

            if (displayPostVMs == null)
            {
                return RedirectToAction("Index");
            }
            DisplayPostVM post = displayPostVMs.FirstOrDefault(x => x.Id == Id);

            if (post != null)
            {
                if (post.ImageData != null || post.ImageMimeType != null)
                {
                    displayPostVMs.Remove(post);
                    Session["NextPosts"] = displayPostVMs;
                    return File(post.ImageData, post.ImageMimeType);
                }
                else
                {
                    PostDTO postDTO = postService.FindById(Id);
                    if (postDTO == null)
                    {
                        var dir = Server.MapPath("~/Content/Images");
                        var path = Path.Combine(dir, "gallery.png");
                        return File(path, "image/jpeg");
                    }
                    return File(postDTO.ImageData, postDTO.ImageMimeType);
                }
            }
            else
            {

                var dir = Server.MapPath("~/Content/Images");
                var path = Path.Combine(dir, "gallery.png");
                return File(path, "image/jpeg");
            }


        }

        /// <summary>
        ///Returns necessary image to author profile. 
        ///</summary>
        ///<param name="id">Id of post.</param>
        ///<returns>Necessary image</returns>
        [AllowAnonymous]
        public ActionResult GetAuthorPostImageToGridItem(int Id)
        {

            List<DisplayPostVM> displayPostVMs = (Session["NextAuthorPosts"] as List<DisplayPostVM>);

            if (displayPostVMs == null)
            {
                return RedirectToAction("Index");
            }
            DisplayPostVM post = displayPostVMs.FirstOrDefault(x => x.Id == Id);

            if (post != null)
            {
                if (post.ImageData != null || post.ImageMimeType != null)
                {

                    displayPostVMs.Remove(post);
                    Session["NextAuthorPosts"] = displayPostVMs;
                    return File(post.ImageData, post.ImageMimeType);
                }
                else
                {
                    PostDTO postDTO = postService.FindById(Id);
                    if (postDTO == null)
                    {
                        var dir = Server.MapPath("~/Content/Images");
                        var path = Path.Combine(dir, "gallery.png");
                        return File(path, "image/jpeg");
                    }
                    return File(postDTO.ImageData, postDTO.ImageMimeType);
                }
            }
            else
            {

                var dir = Server.MapPath("~/Content/Images");
                var path = Path.Combine(dir, "gallery.png");
                return File(path, "image/jpeg");
            }


        }

        /// <summary>
        ///Returns choosed on image grid post image. 
        ///</summary>
        ///<param name="id">Id of post.</param>
        ///<returns>Necessary image</returns>
        [AllowAnonymous]
        public ActionResult GetChoosedPostImage(int Id)
        {


            SinglePostVM post = (Session["ChoosedPost"] as SinglePostVM);

            if (post != null && post.ImageData != null && post.ImageMimeType != null)
            {
                return File(post.ImageData, post.ImageMimeType);
            }
            else
            {
                var dir = Server.MapPath("~/Content/Images/icons");
                var path = Path.Combine(dir, "UserHaveNoPhoto.jpg");
                return File(path, "image/jpeg");
            }

        }

        /// <summary>
        ///Create post view model. 
        ///</summary>
        ///<param name="id">Id of post.</param>
        ///<returns>Post view model </returns>
        private SinglePostVM CreatePostVM(int Id)
        {
            PostDTO postDTO = postService.FindByIdWithIncludes(Id);
            SinglePostVM singlePostVM = _mapper.Map<PostDTO, SinglePostVM>(postDTO);
            RatingVM ratingVM = new RatingVM();
            ratingVM.PostId = Id;
            ratingVM.Likes = ratingService.CountRating(Id);
            ratingVM.IsDisliked = ratingService.IsDislikedByAuthor(User.Identity.GetUserId<int>(), Id);
            ratingVM.IsLiked = ratingService.IsLikedByAuthor(User.Identity.GetUserId<int>(), Id);
            singlePostVM.RatingVM = ratingVM;
            return singlePostVM;
        }
        /// <summary>
        ///Returns choosed post partial view to home. 
        ///</summary>
        ///<param name="id">Id of post.</param>
        ///<returns>Partial view with necessary post</returns>
        [AllowAnonymous]
        public ActionResult GetPostDisplayToHome(int Id)
        {
            SinglePostVM singlePostVM = CreatePostVM(Id);
            Session["ChoosedPost"] = singlePostVM;
            return PartialView("~/Views/Post/Partial/DisplayPostView.cshtml", singlePostVM);
        }
        /// <summary>

WebPhotoAlbum/Views/AuthorProfile/Partial/DeleteConfirm.cshtml
@model WebPhotoAlbum.Models.Post.DeletePostConfirmVM

<div class="postModal-wrapper">

    <div class=" modal-dialog tagModal">

        <div class="modal-content">


            <input type="hidden" name="name" value="@Model.Id" />
            <div class="postModal-closeButton-wrapper">

                <button type="submit" class="postModal-closeButton" data-dismiss="modal" aria-hidden="true">
                    <img src="~/Content/Images/icons/cencelNewPost.svg" alt="cencel" />
                </button>

            </div>
            <div>
                <p class="postModal-title">Delete confirmation</p>
            </div>

            <div class="modal fade" id="CreateTagModal" role="dialog"></div>
            <div>
                <div class="modal-body tagModal-body">
                    @using (Html.BeginForm("DeletePost", "Post",
                                        FormMethod.Post, new { enctype = "multipart/form-data", id = "formNewPost" }))
                    {
                        <div class="description-container">
                            Are you sure that you want delete post?
                        </div>
                        <input type="hidden" value="@Model.Id" name="Id"/>
                        <div class="postModal-footer">
                            <button type="submit" class="postModal-button postModal-button-save" id="btnOk">Delete</button>
                        </div>
                    }
                    </div>

            </div>

        </div>

    </div>

</div>

WebPhotoAlbum/Views/AuthorProfile/Partial/DisplayAuthorPostView.cshtml
@model WebPhotoAlbum.Models.Home.SinglePostVM


<div class="displayPost-wrapper">

    <div class=" modal-dialog  displayPost-modal">

        <div class="modal-content displayPost-content">


            <input type="hidden" name="name" value="@Model.Id" />

            <div>
                <div class="modal-body displayPost-body ">


                    <img src="@Url.Action("GetChoosedPostImage","Post",new { Id=Model.Id})" class="displayPost-image" alt="Alternate Text" />
                    <div class="dropdown-wrapper">
                        <div class="dropdown">
                            <ul class="dropbtn icons btn-right showLeft" onclick="showDropdown()">
                                <li></li>
                                <li></li>
                                <li></li>
                            </ul>
                            <div id="myDropdown" class="dropdown-content">
                                <div href="" onclick="DeletePostModal(@Model.Id)">Delete post</div>


                            </div>
                        </div>
                    </div>
                    <div id="rating"><div>@Html.Partial("~/Views/Post/Partial/DisplayRatingView.cshtml", Model.RatingVM)</div></div>
                    <div class="displayPost-title">TAGS:</div>
                    <div class="displayPost-tags">
                        @if (Model.Tags.Count > 0)
                        {
                            foreach (var item in Model.Tags)
                            {
                                <div class="displayPost-tag"> @item.Title</div>
                            }
                        }
                        else
                        {
                            <div class="displayPost-tag"> Тегов нет</div>
                        }

                    </div>

                    <div class="displayPost-title">DESCRIPTION:</div>
                    @if (!(Model.Description == null || Model.Description == ""))
                    {
                        <div class="displayPost-description">@Model.Description</div>
                    }
                    else
                    {
                        <div class="displayPost-description">Описания нет</div>
                    }
                    <div class="modal fade " id="ConfirmDeletePostModal" role="dialog"></div>
                </div>
            </div>
           
        </div>

    </div>

</div>